### ISSUE TITLE
Cannot use library

### ISSUE THREAD

**Issue by ghost** [promethe42/passport-franceconnect#1]
When implementing this library, i get an error : `ReferenceError: utils is not defined`.
Indeed, in file `PassportAuthenticateWithCustomClaims.js`, there's a call to function `utils.originalURL()` 
(line 29) but `utils` refers to nothing.

Am I missing something ? I'm trying to implement this library properly and I want to avoid making a modified copy in my project.

**Comment by chethan-narayana** [comment]
Hi Team, while trying to register to utl(https://[doc.integ01.dev-franceconnect.fr](https://doc.integ01.dev-franceconnect.fr/inscription)/inscription) get generate client id and secrete page is not loading is there any alternative way of registering

**Comment by cy-polo** [comment]
Hello @GuerricPhalippou, I think I have fixed the problem.
I have made a pull request and it is pending approval.

**Comment by JMLX42** [comment]
Fixed in https://github.com/JMLX42/passport-franceconnect/pull/3
